server:
  servlet:
    session:
      timeout: ${AP_TASK_TIMEOUT:1h}
  http-port: ${AP_PORT:8080}
  http2:
    enabled: ${AP_HTTPS:true}
  ssl:
    enabled: ${AP_HTTPS:true}
    port: ${AP_HTTPS_PORT:8443}
    forced: ${AP_HTTPS_FORCED:false}
    key-store: ${AP_HTTPS_CERT:classpath:config/cert.pfx}
    key-store-password: ${AP_HTTPS_CERT_PASSWORD:123456}
logging:
  level:
    com.github.ansibleproxy: ${AP_LOG_LEVEL:INFO}
  file:
    name: ${AP_LOG_DIR:/opt/ansible_proxy/logs}/log.log
task:
  folder: ${AP_TASK_FOLDER:/opt/ansible_proxy/tasks}/
  clean-file: ${AP_TASK_CLEAN_FILE:true}
  debug: ${AP_TASK_DEBUG:false}
