# The default path for this configuration file is: /opt/ansible_proxy/config/conf.properties
# Or inject the following parameters by using environment variables

# Service http port
APP_PORT=18880
# Enable https
APP_HTTPS=false
# Service https port
APP_HTTPS_PORT=18881
# Forced http jump to https
APP_HTTPS_FORCED=true
# Https certificate file
APP_HTTPS_CERTIFICATE=/opt/ansible_proxy/ssl/ssl_certificate.crt
# Https certificate private key file
APP_HTTPS_CERTIFICATE_PRIVATE_KEY=/opt/ansible_proxy/ssl/ssl_private.key

# Log dir
APP_LOG_DIR=/opt/ansible_proxy/logs
# Log level
APP_LOG_LEVEL=INFO

# Secret private key file
# If it doesn't exist it will be created automatically
APP_SECRET_PRIVATE_KEY=/opt/ansible_proxy/secret/private-key.pem
# Secret public key file
# If it doesn't exist it will be created automatically
APP_SECRET_PUBLIC_KEY=/opt/ansible_proxy/secret/public-key.pem

# Work configuration
AP_TASK_FOLDER=/opt/ansible_proxy/tasks
AP_TASK_TIMEOUT=1h
AP_TASK_CLEAN_FILE=true
AP_TASK_DEBUG=false

